### PR TITLE
Merge pull request #1 from echen102/master

### PR DESCRIPTION
**Pull request by adiga96**
Update_07

### CODE REVIEW

**Comment by adiga96** [comment]
Update_2

**Comment by adiga96** [comment]
Update 08

**Comment by echen102** [comment]
Hi @adiga96 , is this a mistake?

**Comment by echen102** [comment]
Not sure what this is - closing.

**Comment by adiga96** [comment]
> Hi @adiga96 , is this a mistake?

That was by mistake, sorry!

**Pull request closed without merging**
